# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b8f2208403d5a9e5522478338c26eb4116fcc6b23c2f6e3231af677fe1be317b4992ae176271d8440f99d7539c862c63161fb133640dc1ebd9d1509013476a

test:
  secret_key_base: fb746213ad15fe4cd6d8e7a43b47d1089fe0858ef1218021eb6ea635181a0048d6076cd44a68ec592b15ccf16fbbfd7ea20c4da68a6ecaf32069b5e776f75295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
